apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: podman
    component: postgres
